export { productService } from "./product/product.service";
export { searchService } from "./search.service";
export { commentService } from "./comment.service";
export { userService } from "./user.service";
export { historyService } from "./history.service";
export { ratingService } from "./rate.service";
export { customerService } from "./customer.service";
export { orderService } from "./order.service";
export { promoService } from "./promo.service";
